### PR TITLE
Support multiple assets

### PR DESCRIPTION
**Pull request by shumon84**
Support multiple assets by changing type of zipData from simple string to map [string] string.

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thanks @shumon84 what about adding some unit tests on this one?

**Comment by shumon84** [comment]
Thanks for quick reply.
I will add unit tests as you said.

**Comment by shumon84** [comment]
@jcchavezs I added unit tests to fs_test.go

**Comment by jcchavezs** [comment]
Sorry for the late response. Does it make sense to call it `namespace` instead of `name`? What do you think?

**Comment by shumon84** [comment]
I agree with you.

**Pull request closed without merging**
